import { GuardrailRule } from './types';

export const DEFAULT_GUARDRAIL_RULES: GuardrailRule[] = [
  // --- LAYER 1: DETERMINISTIC REGEX & CHECKSUMS ---
  {
    id: 'rule-aws-key',
    name: 'AWS Access Key ID',
    category: 'api_keys',
    description: 'Matches standard 20-character AWS Access Key IDs (AKIA...)',
    layer: 1,
    pattern: '\\b(AKIA|ABIA|ACCA|ASIA)[0-9A-Z]{16}\\b',
    enabled: true,
    confidenceThreshold: 0.95,
    redactionStyle: 'label',
    customLabel: 'AWS_ACCESS_KEY',
    builtIn: true,
    severity: 'critical',
  },
  {
    id: 'rule-aws-secret',
    name: 'AWS Secret Access Key',
    category: 'credentials',
    description: 'Matches 40-character AWS Secret Keys in proximity to AWS identifiers',
    layer: 1,
    pattern: '(?i)(?:aws_secret_access_key|aws_secret|secret_key|aws_key)\\s*[:=]?\\s*([a-zA-Z0-9/+=]{40})',
    enabled: true,
    confidenceThreshold: 0.9,
    redactionStyle: 'label',
    customLabel: 'AWS_SECRET_KEY',
    builtIn: true,
    severity: 'critical',
  },
  {
    id: 'rule-github-token',
    name: 'GitHub Personal Access Token',
    category: 'api_keys',
    description: 'Detects GitHub PATs (classic ghp_ and fine-grained github_pat_)',
    layer: 1,
    pattern: '\\b(ghp_[a-zA-Z0-9]{36}|github_pat_[a-zA-Z0-9_]{40,})\\b',
    enabled: true,
    confidenceThreshold: 0.98,
    redactionStyle: 'label',
    customLabel: 'GITHUB_TOKEN',
    builtIn: true,
    severity: 'critical',
  },
  {
    id: 'rule-openai-key',
    name: 'OpenAI / AI Studio API Key',
    category: 'api_keys',
    description: 'Matches API keys prefixed with sk-, sk-proj-, or AIza (Gemini / Google API)',
    layer: 1,
    pattern: '\\b(sk-(?:proj-)?[a-zA-Z0-9_-]{20,100}|AIza[0-9A-Za-z-_]{35})\\b',
    enabled: true,
    confidenceThreshold: 0.95,
    redactionStyle: 'label',
    customLabel: 'AI_API_KEY',
    builtIn: true,
    severity: 'critical',
  },
  {
    id: 'rule-slack-token',
    name: 'Slack Webhook / Bot Token',
    category: 'api_keys',
    description: 'Matches Slack bot tokens and incoming webhook URLs',
    layer: 1,
    pattern: '\\b(xox[baprs]-[0-9]{10,13}-[0-9]{10,13}-[a-zA-Z0-9]{24,32}|https:\\/\\/hooks\\.slack\\.com\\/services\\/T[a-zA-Z0-9_]+\\/B[a-zA-Z0-9_]+\\/[a-zA-Z0-9_]+)\\b',
    enabled: true,
    confidenceThreshold: 0.95,
    redactionStyle: 'label',
    customLabel: 'SLACK_TOKEN',
    builtIn: true,
    severity: 'high',
  },
  {
    id: 'rule-jwt',
    name: 'JSON Web Token (JWT)',
    category: 'credentials',
    description: 'Detects standard base64 encoded JWTs (header.payload.signature)',
    layer: 1,
    pattern: '\\b(eyJ[a-zA-Z0-9_-]{10,}\\.eyJ[a-zA-Z0-9_-]{10,}\\.[a-zA-Z0-9_-]{10,})\\b',
    enabled: true,
    confidenceThreshold: 0.92,
    redactionStyle: 'mask',
    customLabel: 'JWT_TOKEN',
    builtIn: true,
    severity: 'high',
  },
  {
    id: 'rule-private-key',
    name: 'Private Key Block',
    category: 'credentials',
    description: 'Matches RSA, SSH, EC, and standard PEM private key headers',
    layer: 1,
    pattern: '-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----[\\s\\S]*?-----END (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----|-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----',
    enabled: true,
    confidenceThreshold: 1.0,
    redactionStyle: 'label',
    customLabel: 'PRIVATE_KEY_BLOCK',
    builtIn: true,
    severity: 'critical',
  },
  {
    id: 'rule-db-uri',
    name: 'Database Connection String',
    category: 'credentials',
    description: 'Matches postgres, mongodb, mysql, and redis URIs containing credentials',
    layer: 1,
    pattern: '(?:postgres|postgresql|mysql|mongodb(?:\\+srv)?|redis):\\/\\/[^\\s:@]+:[^\\s@]+@[^\\s/]+',
    enabled: true,
    confidenceThreshold: 0.95,
    redactionStyle: 'label',
    customLabel: 'DATABASE_CONN_URI',
    builtIn: true,
    severity: 'critical',
  },
  {
    id: 'rule-credit-card',
    name: 'Credit Card Number (Luhn-checked)',
    category: 'financial',
    description: 'Detects Visa, MasterCard, Amex, and Discover numbers validated with Luhn algorithm',
    layer: 1,
    pattern: '\\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|6(?:011|5[0-9]{2})[0-9]{12}|(?:2131|1800|35\\d{3})\\d{11}|\\d{4}[ -]?\\d{4}[ -]?\\d{4}[ -]?\\d{4})\\b',
    enabled: true,
    confidenceThreshold: 0.9,
    redactionStyle: 'category',
    customLabel: 'CREDIT_CARD',
    builtIn: true,
    severity: 'critical',
  },
  {
    id: 'rule-ssn',
    name: 'Social Security Number (SSN)',
    category: 'pii',
    description: 'Matches US Social Security Numbers in standard and spoken formats',
    layer: 1,
    pattern: '\\b(?!000|666|9\\d{2})\\d{3}[- ]?(?!00)\\d{2}[- ]?(?!0000)\\d{4}\\b',
    enabled: true,
    confidenceThreshold: 0.9,
    redactionStyle: 'category',
    customLabel: 'US_SSN',
    builtIn: true,
    severity: 'critical',
  },
  {
    id: 'rule-email',
    name: 'Email Address',
    category: 'pii',
    description: 'Detects corporate and personal email addresses',
    layer: 1,
    pattern: '\\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}\\b',
    enabled: true,
    confidenceThreshold: 0.85,
    redactionStyle: 'mask',
    customLabel: 'EMAIL',
    builtIn: true,
    severity: 'medium',
  },
  {
    id: 'rule-phone',
    name: 'North American / International Phone Number',
    category: 'pii',
    description: 'Matches telephone formats: (123) 456-7890, 123-456-7890, +1 123 456 7890',
    layer: 1,
    pattern: '\\b(?:\\+?[1-9]\\d{0,2}[-.\\s]?)?(?:\\(\\d{3}\\)|\\d{3})[-.\\s]\\d{3}[-.\\s]\\d{4}\\b',
    enabled: true,
    confidenceThreshold: 0.85,
    redactionStyle: 'label',
    customLabel: 'PHONE_NUMBER',
    builtIn: true,
    severity: 'medium',
  },
  {
    id: 'rule-ip',
    name: 'IP Address (IPv4)',
    category: 'pii',
    description: 'Detects public and private IPv4 addresses',
    layer: 1,
    pattern: '\\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\\b',
    enabled: true,
    confidenceThreshold: 0.8,
    redactionStyle: 'mask',
    customLabel: 'IP_ADDRESS',
    builtIn: true,
    severity: 'low',
  },

  // --- LAYER 2: NER & CONTEXT-AWARE RECOGNIZERS (Presidio/spaCy style) ---
  {
    id: 'rule-ner-person',
    name: 'Person Names (NER / Presidio)',
    category: 'pii',
    description: 'Context-aware named entity recognition for employee and customer names',
    layer: 2,
    enabled: true,
    confidenceThreshold: 0.75,
    redactionStyle: 'label',
    customLabel: 'PERSON_NAME',
    builtIn: true,
    severity: 'medium',
  },
  {
    id: 'rule-ner-financial-amt',
    name: 'Sensitive Financials & Compensation',
    category: 'financial',
    description: 'Detects unreleased salaries, budget figures, and deal terms ($500k, $1.2M valuation)',
    layer: 2,
    pattern: '\\$(?:\\d{1,3}(?:,\\d{3})*|\\d+)(?:\\.\\d+)?(?:\\s*(?:thousand|million|billion|k|m|b))?\\b|\\b\\d+\\s*(?:thousand|million|billion)\\s*dollars\\b',
    enabled: true,
    confidenceThreshold: 0.85,
    redactionStyle: 'label',
    customLabel: 'CONFIDENTIAL_FINANCIALS',
    builtIn: true,
    severity: 'high',
  },
  {
    id: 'rule-ner-codename',
    name: 'Internal Project Codename',
    category: 'credentials',
    description: 'Detects enterprise acquisition codenames and unannounced initiative keywords',
    layer: 2,
    pattern: '(?i)\\b(?:Project\\s+(?:Titan|Apollo|Chronos|Phoenix|Nebula|Oasis)|Operation\\s+[A-Z][a-z]+|Acquisition\\s+of\\s+[A-Z][a-zA-Z0-9]+)\\b',
    enabled: true,
    confidenceThreshold: 0.8,
    redactionStyle: 'label',
    customLabel: 'CONFIDENTIAL_CODENAME',
    builtIn: true,
    severity: 'high',
  },

  // --- LAYER 3: SPOKEN-CUE TRIGGER PHRASES (Proximity Window) ---
  {
    id: 'rule-spoken-password',
    name: 'Spoken Password / Credentials Lead-in',
    category: 'spoken_cue',
    description: 'Captures "my password is...", "the login is...", "credentials are..." and redacts adjacent token window',
    layer: 3,
    triggerPhrases: [
      'my password is',
      'the password is',
      'password is',
      'the login is',
      'login is',
      'credentials are',
      'the secret is',
      'passcode is',
      'my pin is',
      'pin number is',
      'the pin is',
      'wifi password is',
      'root password is',
      'master key is',
      'auth key is',
      'temporary token is',
      'one time passcode is',
      'otp is',
    ],
    enabled: true,
    confidenceThreshold: 0.85,
    redactionStyle: 'label',
    customLabel: 'SPOKEN_SECRET',
    builtIn: true,
    severity: 'critical',
  },
];
