"""Default Guardrail Rule Catalog for VisionCraft (FR-012, FR-013, FR-017).

Provides high-precision deterministic detection patterns for credentials,
API tokens, PII, financial identifiers, and spoken confidential lead-ins.
"""

from typing import List
from visioncraft.types import GuardrailRule

DEFAULT_GUARDRAIL_RULES: List[GuardrailRule] = [
    # --- LAYER 1: DETERMINISTIC REGEX & CHECKSUMS ---
    GuardrailRule(
        id="rule-aws-key",
        name="AWS Access Key ID",
        category="api_keys",
        description="Matches standard 20-character AWS Access Key IDs (AKIA...)",
        layer=1,
        pattern=r"\b(AKIA|ABIA|ACCA|ASIA)[0-9A-Z]{16}\b",
        enabled=True,
        confidence_threshold=0.95,
        redaction_style="label",
        custom_label="AWS_ACCESS_KEY",
        built_in=True,
        severity="critical",
    ),
    GuardrailRule(
        id="rule-aws-secret",
        name="AWS Secret Access Key",
        category="credentials",
        description="Matches 40-character AWS Secret Keys in proximity to AWS identifiers",
        layer=1,
        pattern=r"(?i)(?:aws_secret_access_key|aws_secret|secret_key|aws_key)\s*[:=]?\s*([a-zA-Z0-9/+=]{40})",
        enabled=True,
        confidence_threshold=0.9,
        redaction_style="label",
        custom_label="AWS_SECRET_KEY",
        built_in=True,
        severity="critical",
    ),
    GuardrailRule(
        id="rule-github-token",
        name="GitHub Personal Access Token",
        category="api_keys",
        description="Detects GitHub PATs (classic ghp_ and fine-grained github_pat_)",
        layer=1,
        pattern=r"\b(ghp_[a-zA-Z0-9]{36}|github_pat_[a-zA-Z0-9_]{40,})\b",
        enabled=True,
        confidence_threshold=0.98,
        redaction_style="label",
        custom_label="GITHUB_TOKEN",
        built_in=True,
        severity="critical",
    ),
    GuardrailRule(
        id="rule-openai-key",
        name="OpenAI / AI Studio API Key",
        category="api_keys",
        description="Matches API keys prefixed with sk-, sk-proj-, or AIza (Gemini / Google API)",
        layer=1,
        pattern=r"\b(sk-(?:proj-)?[a-zA-Z0-9_-]{20,100}|AIza[0-9A-Za-z-_]{35})\b",
        enabled=True,
        confidence_threshold=0.95,
        redaction_style="label",
        custom_label="AI_API_KEY",
        built_in=True,
        severity="critical",
    ),
    GuardrailRule(
        id="rule-slack-token",
        name="Slack Webhook / Bot Token",
        category="api_keys",
        description="Matches Slack bot tokens and incoming webhook URLs",
        layer=1,
        pattern=r"\b(xox[baprs]-[0-9]{10,13}-[0-9]{10,13}-[a-zA-Z0-9]{24,32}|https:\/\/hooks\.slack\.com\/services\/T[a-zA-Z0-9_]+\/B[a-zA-Z0-9_]+\/[a-zA-Z0-9_]+)\b",
        enabled=True,
        confidence_threshold=0.95,
        redaction_style="label",
        custom_label="SLACK_TOKEN",
        built_in=True,
        severity="high",
    ),
    GuardrailRule(
        id="rule-jwt",
        name="JSON Web Token (JWT)",
        category="credentials",
        description="Detects standard base64 encoded JWTs (header.payload.signature)",
        layer=1,
        pattern=r"\b(eyJ[a-zA-Z0-9_-]{10,}\.eyJ[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,})\b",
        enabled=True,
        confidence_threshold=0.92,
        redaction_style="mask",
        custom_label="JWT_TOKEN",
        built_in=True,
        severity="high",
    ),
    GuardrailRule(
        id="rule-private-key",
        name="Private Key Block",
        category="credentials",
        description="Matches RSA, SSH, EC, and standard PEM private key headers",
        layer=1,
        pattern=r"-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----[\s\S]*?-----END (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----|-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----",
        enabled=True,
        confidence_threshold=1.0,
        redaction_style="label",
        custom_label="PRIVATE_KEY_BLOCK",
        built_in=True,
        severity="critical",
    ),
    GuardrailRule(
        id="rule-db-uri",
        name="Database Connection String",
        category="credentials",
        description="Matches PostgreSQL, MySQL, MongoDB, Redis, and MSSQL URIs containing embedded passwords",
        layer=1,
        pattern=r"\b(?:postgres(?:ql)?|mysql|mongodb(?:\+srv)?|redis|mssql):\/\/[a-zA-Z0-9_]+:[^@\s]+@[a-zA-Z0-9.-]+(?::[0-9]+)?(?:\/[a-zA-Z0-9_.-]*)?\b",
        enabled=True,
        confidence_threshold=0.95,
        redaction_style="label",
        custom_label="DATABASE_CONN_URI",
        built_in=True,
        severity="critical",
    ),
    GuardrailRule(
        id="rule-credit-card",
        name="Credit Card Number (Luhn-checked)",
        category="financial",
        description="Detects Visa, MasterCard, Amex, and Discover numbers validated with Luhn algorithm",
        layer=1,
        pattern=r"\b(?:4[0-9]{12}(?:[0-9]{3})?|5[1-5][0-9]{14}|3[47][0-9]{13}|3(?:0[0-5]|[68][0-9])[0-9]{11}|6(?:011|5[0-9]{2})[0-9]{12}|(?:2131|1800|35\d{3})\d{11}|\d{4}[ -]?\d{4}[ -]?\d{4}[ -]?\d{4})\b",
        enabled=True,
        confidence_threshold=0.9,
        redaction_style="category",
        custom_label="CREDIT_CARD",
        built_in=True,
        severity="critical",
    ),
    GuardrailRule(
        id="rule-ssn",
        name="Social Security Number (SSN)",
        category="pii",
        description="Matches US Social Security Numbers in standard and spoken formats",
        layer=1,
        pattern=r"\b(?!000|666|9\d{2})\d{3}[- ]?(?!00)\d{2}[- ]?(?!0000)\d{4}\b",
        enabled=True,
        confidence_threshold=0.9,
        redaction_style="category",
        custom_label="US_SSN",
        built_in=True,
        severity="critical",
    ),
    GuardrailRule(
        id="rule-email",
        name="Email Address",
        category="pii",
        description="Matches standard and speech-normalized email addresses",
        layer=1,
        pattern=r"\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b",
        enabled=True,
        confidence_threshold=0.92,
        redaction_style="label",
        custom_label="EMAIL",
        built_in=True,
        severity="medium",
    ),
    GuardrailRule(
        id="rule-phone",
        name="North American / International Phone Number",
        category="pii",
        description="Matches telephone formats: (123) 456-7890, 123-456-7890, +1 123 456 7890",
        layer=1,
        pattern=r"\b(?:\+?[1-9]\d{0,2}[-.\s]?)?(?:\(\d{3}\)|\d{3})[-.\s]\d{3}[-.\s]\d{4}\b",
        enabled=True,
        confidence_threshold=0.85,
        redaction_style="label",
        custom_label="PHONE_NUMBER",
        built_in=True,
        severity="medium",
    ),
    GuardrailRule(
        id="rule-ipv4",
        name="Private & Public IPv4 Address",
        category="pii",
        description="Matches dotted decimal IPv4 network addresses",
        layer=1,
        pattern=r"\b(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\b",
        enabled=True,
        confidence_threshold=0.88,
        redaction_style="mask",
        custom_label="IP_ADDRESS",
        built_in=True,
        severity="low",
    ),

    # --- LAYER 2: CONTEXTUAL NER (Presidio / spaCy) ---
    GuardrailRule(
        id="rule-ner-person",
        name="Person / Participant Name (NER)",
        category="pii",
        description="Identifies individual names in conversational context",
        layer=2,
        enabled=True,
        confidence_threshold=0.82,
        redaction_style="label",
        custom_label="PERSON_NAME",
        built_in=True,
        severity="low",
    ),

    # --- LAYER 3: SPOKEN SECRET CUES & PROXIMITY ---
    GuardrailRule(
        id="rule-spoken-password",
        name="Spoken Password Lead-in Cue",
        category="spoken_cue",
        description="Identifies voice cues ('my password is...', 'the secret code is...') and redacts following token window",
        layer=3,
        trigger_phrases=[
            "the pass is",
            "the pass",
            "my pass is",
            "my pass",
            "pass is",
            "pass:",
            "the password is",
            "my password is",
            "password is",
            "password:",
            "the pw is",
            "the pw",
            "pw is",
            "pw:",
            "the pwd is",
            "the pwd",
            "pwd is",
            "pwd:",
            "passwrd is",
            "the passcode is",
            "my passcode is",
            "passcode is",
            "pass code is",
            "pass code:",
            "the creds are",
            "the creds is",
            "the creds",
            "creds are",
            "creds is",
            "creds:",
            "my creds are",
            "login creds are",
            "login creds:",
            "the login is",
            "the login",
            "login is",
            "login:",
            "the temp pass is",
            "temp pass is",
            "temporary pass is",
            "temp password is",
            "wifi pass is",
            "wifi pass",
            "wifi password is",
            "wifi password:",
            "root pass is",
            "root pass",
            "root password is",
            "root password:",
            "admin pass is",
            "admin pass",
            "admin password is",
            "admin password:",
            "db pass is",
            "db pass",
            "db password is",
            "db password:",
            "db creds are",
            "db creds is",
            "db creds",
            "database creds are",
            "database creds:",
            "conn str is",
            "conn str",
            "conn string is",
            "connection string is",
            "conn str:",
            "the token is",
            "the token",
            "token is",
            "token:",
            "auth token is",
            "access token is",
            "bearer token is",
            "bearer is",
            "jwt token is",
            "the secret key is",
            "secret key is",
            "secret key:",
            "my secret key is",
            "the secret is",
            "my secret is",
            "secret is",
            "secret:",
            "the api key is",
            "api key is",
            "api key:",
            "my api key is",
            "api token is",
            "app secret is",
            "client secret is",
            "the master key is",
            "master key is",
            "the private key is",
            "private key is",
            "the pin is",
            "the pin",
            "my pin is",
            "pin is",
            "pin:",
            "pin code is",
            "pin number is",
            "acc no is",
            "acc no:",
            "acct no is",
            "acct no:",
            "acct num is",
            "acct num:",
            "account no is",
            "account number is",
            "cvv is",
            "cvv:",
            "cvv code is",
            "cvv number is",
            "routing no is",
            "routing number is",
            "dob is",
            "dob:",
            "date of birth is",
            "ssn is",
            "ssn:",
            "social is",
            "social security is",
            "social security number is",
        ],
        enabled=True,
        confidence_threshold=0.9,
        redaction_style="label",
        custom_label="SPOKEN_SECRET",
        built_in=True,
        severity="critical",
    ),
    GuardrailRule(
        id="rule-confidential-mna",
        name="Corporate M&A / Project Codename",
        category="credentials",
        description="Identifies confidential project names and strategic codenames",
        layer=3,
        trigger_phrases=[
            "project titan",
            "project apollo",
            "project blue",
            "project alpha",
            "project phoenix",
            "project vanguard",
        ],
        enabled=True,
        confidence_threshold=0.88,
        redaction_style="category",
        custom_label="CONFIDENTIAL_CODENAME",
        built_in=True,
        severity="high",
    ),
    GuardrailRule(
        id="rule-confidential-financial",
        name="Confidential Financial Figures & M&A Values",
        category="financial",
        description="Detects confidential deal amounts, revenue projections, and M&A pricing",
        layer=1,
        pattern=r"\$\s*\d+(?:\.\d+)?\s*(?:million|billion|trillion|k|m|b)\b",
        enabled=True,
        confidence_threshold=0.85,
        redaction_style="label",
        custom_label="CONFIDENTIAL_FINANCIALS",
        built_in=True,
        severity="high",
    ),
]
